# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
- Feature/*

pr:
 branches:
   include:
     - Feature
     
pool:
  name: default
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  DotNetVersion: '8.0.100'



steps:


- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'MSBuild'
    projectKey: 'XXX'
    projectName: '.NET MAUI Webshop'

- task: UseDotNet@2
  displayName: .NET Version
  inputs:
    packageType: 'sdk'
    version: '$(DotNetVersion)'
    
- task: PowerShell@2
  displayName: Install .NET MAUI
  inputs:
    targetType: 'inline'
    script: |
      & dotnet nuget locals all --clear
      & dotnet workload install maui --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json
      & dotnet workload install android ios maccatalyst tvos macos maui wasm-tools maui-maccatalyst --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json --source https://api.nuget.org/v3/index.json

- task: PowerShell@2
  continueOnError: true 
  displayName: Build and Test solution
  inputs:
    targetType: 'inline'
    script: |
      & dotnet dotnet build .\Webshop.Maui -c Release -f net8.0-windows10.0.19041.0 /p:RuntimeIdentifierOverride=win10-x64
      & dotnet test --logger trx --collect "Code coverage"

# - task: DotNetCoreCLI@2
#   continueOnError: true
#   inputs:
#     command: 'test'
#     arguments: '--collect "Code coverage"'
# - script: dotnet test --logger trx --collect "Code coverage"
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'


